//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Constantes {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Constantes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8D12BBE3-950E-487F-A24B-BFAB261D1059.
        /// </summary>
        public static string AREA_ENGENHARIA {
            get {
                return ResourceManager.GetString("AREA_ENGENHARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6217BA88-9FC9-4EAA-B6E6-CE4D950F19A9.
        /// </summary>
        public static string AREA_SAUDE {
            get {
                return ResourceManager.GetString("AREA_SAUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 08E0CC41-A608-4C54-8DF7-22F8B5688A96.
        /// </summary>
        public static string AREA_TI {
            get {
                return ResourceManager.GetString("AREA_TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar o método..
        /// </summary>
        public static string ERRO_EXEC_METODO {
            get {
                return ResourceManager.GetString("ERRO_EXEC_METODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar consulta no repositorio..
        /// </summary>
        public static string ERRO_REPOSITORIO {
            get {
                return ResourceManager.GetString("ERRO_REPOSITORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6D672B19-8F61-413E-8277-3351DDDC5C56.
        /// </summary>
        public static string PERFIL_ADMIN {
            get {
                return ResourceManager.GetString("PERFIL_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5AB0D5A4-A8EE-4B3F-946F-1085D0BBE67D.
        /// </summary>
        public static string PERFIL_ALUNO {
            get {
                return ResourceManager.GetString("PERFIL_ALUNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a F0292581-FD91-475F-B751-0604491EA3F5.
        /// </summary>
        public static string PERFIL_COORDENADOR {
            get {
                return ResourceManager.GetString("PERFIL_COORDENADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A8D3371E-84E4-4A29-8CF4-CA92AF25622F.
        /// </summary>
        public static string PERFIL_PROFESSOR {
            get {
                return ResourceManager.GetString("PERFIL_PROFESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FC7DF6C4-46AC-48F4-B279-DF38452DB772.
        /// </summary>
        public static string SENHA_CHAVE {
            get {
                return ResourceManager.GetString("SENHA_CHAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha inválidos.
        /// </summary>
        public static string USUARIO_NAO_AUTORIZADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_AUTORIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
